title: Rafael Sermenho
email: rafael.sermenho@gmail.com
description: Meu site pessoal onde eu escrevo sobre tecnologia e o que mais vier na mente.
baseurl: "/rafaelsermenho"
url: "https://rafaelsermenho.dev"
twitter_username: rafaelsermenho  
github_username:  rafaelsermenho

# Build settings
remote-theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

google_analytics:   UA-44709741-6
